### PR TITLE
Run pytest from within Jython and as part of mvn test stage

### PR DESCRIPTION
**Pull request by raquel-ucl**
It doesn't work yet because by default tests in maven are run before the plugin that installs pytest. Need to modify the POM to run the jython compile plugin earlier, or the tests later.

### CODE REVIEW

**Comment by raquel-ucl** [comment]
Now the plugin that installs pytest is run before surefire, but it's still not finding pytest.

**Comment by jenshnielsen** [comment]
You could try calling it as 

```
python -m pytest
```

or 

```
jython -m pytest
``` 
perhaps to avoid having the bin script on path

**Comment by raquel-ucl** [comment]
I hadn't seen your comment. I'm not sure how to do that, I'm calling pytest from within python. It seems to work now, just adding aparam to run only nammu tests.

**Comment by raquel-ucl** [comment]
It works now, please review.

**Comment by raquel-ucl** [comment]
I still can't quite understand why I need to put the path to the installation of the modules in the test class AppTest.java, but this is not needed from App.java.

**Comment by jenshnielsen** [comment]
Never mind we can always revisit that. Does this run the tests or do we need to modify the jenkins script?

**Comment by raquel-ucl** [comment]
No need to change anything in the jenkins scripts. Tests are being run already.

**Comment by raquel-ucl** [comment]
When tests fail in py.test, this is not propagated to Java's PythonInterpreter, need to find out how to fix that.

**Pull request merged**
